### ISSUE TITLE
Auto potion quaffer

### ISSUE THREAD

**Issue by Thridi** [xekon/AardwolfMudlet#1]
Attached are my alias and scripts for a potion auto-quaffer. I have spoken to Lasher about this and as long as you are actively watching the screen (which goes for killing in general anyways), it is not a violation of the rules.

[aardwolf_quaffer.txt](https://github.com/xekon/AardwolfMudlet/files/4007632/aardwolf_quaffer.txt)

**Comment by Jieiku** [comment]
I would suggest implementing a script that monitors your last keyboard input and if its more than a couple minutes then dont quaf a potion. If you happen to need to emergency AFK to answer phone or get the door or whatever, it would be better to be dead than in jail or nuked. I am hoping to have some free time to play again soon. Thanks for the script, will take a look at it :)

Edit: in addition when the script sees that you have been AFK/IDLE for 2+ minutes instead of Quaffing it could send a visual/audio alert letting you know that it wont quaf because of being idle.
